# Generated by Django 4.1.13 on 2024-08-14 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Título")),
                ("author", models.CharField(max_length=100, verbose_name="Autor")),
                ("url", models.URLField(verbose_name="Link do Goodreeds")),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("pt", "Português"),
                            ("en", "Inglês"),
                            ("es", "Espanhol"),
                            ("fr", "Francês"),
                        ],
                        max_length=2,
                        verbose_name="Língua do Livro",
                    ),
                ),
                (
                    "landed_to",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Requisitado por",
                    ),
                ),
                (
                    "landed_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Requisitado no dia"
                    ),
                ),
            ],
            options={
                "verbose_name": "Livro",
                "verbose_name_plural": "Livros",
                "ordering": ["title"],
            },
        ),
    ]
