# Generated by Django 4.1.13 on 2024-08-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="language",
            field=models.CharField(max_length=20, verbose_name="Língua do Livro"),
        ),
    ]
