# Generated by Django 4.1.13 on 2024-08-13 21:13

from django.db import migrations, models
import wagtail.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        help_text="ex: E-mail, Tel, ...",
                        max_length=255,
                        verbose_name="Tipo de Contacto",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        max_length=255, verbose_name="Informação do Contacto"
                    ),
                ),
            ],
            options={
                "verbose_name": "contacto",
                "verbose_name_plural": "contactos",
                "ordering": ["kind", "text"],
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="MediaLinks",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_name",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("messenger", "Messenger"),
                            ("twitter", "Twitter"),
                            ("pinterest", "Pinterest"),
                            ("whatsapp", "WhatsApp"),
                            ("linkedin", "LinkedIn"),
                            ("youtube", "Youtube"),
                            ("tiktok", "TikTok"),
                            ("reddit", "Reddit"),
                            ("discord", "Discord"),
                            ("telegram", "Telegram"),
                            ("medium", "Medium"),
                        ],
                        max_length=63,
                        verbose_name="Nome do Icon",
                    ),
                ),
                ("url", models.URLField()),
            ],
            options={
                "verbose_name": "rede social",
                "verbose_name_plural": "redes sociais",
                "ordering": ["icon_name"],
            },
            bases=(wagtail.models.PreviewableMixin, models.Model),
        ),
    ]
