# Generated by Django 4.1.13 on 2024-08-13 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="kind",
            field=models.CharField(
                choices=[
                    ("phone", "Telemóvel"),
                    ("envelope-fill", "E-Mail"),
                    ("home", "Morada"),
                ],
                max_length=63,
                verbose_name="Tipo de contacto",
            ),
        ),
    ]
