# Generated by Django 4.1.13 on 2024-08-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0003_sponsor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sponsor",
            options={
                "ordering": ["name"],
                "verbose_name": "Patrocinador",
                "verbose_name_plural": "Patrocinadores",
            },
        ),
        migrations.AlterField(
            model_name="contact",
            name="kind",
            field=models.CharField(
                choices=[
                    ("phone", "Telemóvel"),
                    ("envelope-fill", "E-Mail"),
                    ("house-fill", "Morada"),
                ],
                max_length=63,
                verbose_name="Tipo de contacto",
            ),
        ),
    ]
