# Generated by Django 4.1.13 on 2024-08-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0005_contact_show_in_footer"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="title",
            field=models.CharField(
                default="", max_length=255, verbose_name="Título do Contacto"
            ),
            preserve_default=False,
        ),
    ]
