# Generated by Django 4.1.13 on 2024-08-16 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0006_contact_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contact",
            options={
                "ordering": ["title", "kind", "text"],
                "verbose_name": "contacto",
                "verbose_name_plural": "contactos",
            },
        ),
    ]
