# Generated by Django 4.1.13 on 2024-08-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0009_event"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="url",
            field=models.URLField(blank=True, null=True, verbose_name="Link"),
        ),
    ]
