# Generated by Django 4.1.13 on 2024-08-13 13:01

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("wagtailimages", "0024_index_image_file_hash"),
        ("home", "0002_create_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="banner_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_subtitle",
            field=models.CharField(
                max_length=100, null=True, verbose_name="Sub-Título"
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="banner_title",
            field=models.CharField(max_length=100, null=True, verbose_name="Título"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    (
                        "home_content",
                        wagtail.blocks.StructBlock(
                            [
                                ("title", wagtail.blocks.CharBlock(required=True)),
                                ("body", wagtail.blocks.RichTextBlock(required=True)),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        required=True
                                    ),
                                ),
                                (
                                    "image_left",
                                    wagtail.blocks.BooleanBlock(required=True),
                                ),
                                ("btn_text", wagtail.blocks.CharBlock(required=False)),
                                ("btn_url", wagtail.blocks.CharBlock(required=False)),
                                (
                                    "btn_page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=False,
            ),
        ),
    ]
